[profile.default]
src      = "src"
test     = "test"
script   = "script"
out      = "out"
libs     = ["lib"]
solc     = "0.8.24"
optimizer        = true
optimizer_runs   = 200
via_ir           = false
evm_version      = "paris"   # Arc EVM compatible

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"

[etherscan]
arc_testnet = { key = "${ETHERSCAN_KEY}", url = "https://testnet.arcscan.app/api" }

[fmt]
line_length  = 100
tab_width    = 4
bracket_spacing = true
