import type { Metadata } from "next";
import Link from "next/link";
import { ExternalLink } from "lucide-react";

export const metadata: Metadata = {
  title: "FAQ – OMdot.fun",
  description: "Frequently asked questions about OMdot.fun — prediction markets, launchpad, fees, wallets, verification badge, and Omero rewards.",
  alternates: { canonical: "https://omdot.fun/faq" },
};

type Section = {
  title: string;
  items: { q: string; a: React.ReactNode }[];
};

const SECTIONS: Section[] = [
  {
    title: "Prediction markets",
    items: [
      {
        q: "What is a prediction market on OMdot.fun?",
        a: (
          <>
            A prediction market lets you bet on the outcome of an event: crypto, politics, sports, economy, culture, elections, or a custom / IRL event (contest, stream, match between friends, etc.). You can create Yes/No or multi-option markets. Winners are paid automatically from the losers&apos; stakes. It is peer-to-peer, on-chain.
          </>
        ),
      },
      {
        q: "How does the payout work?",
        a: (
          <>
            Each market outcome has a price that reflects the community&apos;s estimated probability. If an outcome is trading at 30%, you can buy a share for ~$0.30 and receive $1 if it resolves YES — a 3× return. If it trades at 70%, the payout is smaller because the community sees it as more likely.
            <br /><br />
            Example: you bet $10 on an outcome at 25%. If it resolves YES, you receive ~$40. If it resolves NO, you lose your $10. There is no minimum bet — the only lower limit is the Solana network fee (~$0.001).
          </>
        ),
      },
      {
        q: "How much does it cost to create a market?",
        a: "To create a market, you pay 2 USDC or 500,000 ClawdTrust.",
      },
      {
        q: "How much does the market creator earn?",
        a: (
          <>
            The creator receives 1% of the volume traded on their market. You can also earn Omero — more Omero if you create or trade with $ClawdTrust — and 1% of the revenue generated by your referrals who create markets. We no longer distribute OCTO. Rewards are now in Omero.
          </>
        ),
      },
      {
        q: "Who owns a market?",
        a: "The first person to create a topic owns it. No one else can copy or relaunch the same market.",
      },
      {
        q: "Which tokens can be used?",
        a: "USDC and ClawdTrust ($CLAWDTRUST).",
      },
      {
        q: "How do I create a market?",
        a: (
          <ol className="list-decimal list-inside space-y-1">
            <li>Go to <a href="https://omdot.fun" className="text-violet-600 dark:text-violet-400 underline underline-offset-2">omdot.fun</a></li>
            <li>Connect your wallet (Solflare recommended, Phantom also works — see <em>Which wallets should I use?</em> below)</li>
            <li>Click <strong>+ Create a Market</strong></li>
            <li>Pay 2 USDC or 500,000 ClawdTrust</li>
            <li>Fill in a precise title, options, resolution date, and criteria</li>
            <li>Publish, then share the link on X, Discord, Telegram, and in your communities</li>
          </ol>
        ),
      },
      {
        q: "How is a market resolved?",
        a: "On the scheduled date, according to the criteria and sources defined at creation. Payouts are automatic.",
      },
      {
        q: "What if the creator doesn't resolve the market on time?",
        a: (
          <>
            If a market creator fails to resolve after the resolution date, the OMdot.fun team can step in to resolve or cancel the market based on the original criteria. In the case of cancellation, all stakes are returned to participants. You can report an unresolved market via our Discord or Telegram.
          </>
        ),
      },
      {
        q: "What if I disagree with a resolution?",
        a: (
          <>
            If you believe a market was resolved incorrectly or in bad faith, report it through our Discord with the market link and your reasoning. Our moderation team reviews contested resolutions and can override a decision if it clearly violates the stated criteria. We aim to respond within 48 hours.
          </>
        ),
      },
      {
        q: "How do I claim my winnings?",
        a: (
          <>
            Winnings accumulate in your OMdot.fun balance automatically when a market resolves. To withdraw:
            <ol className="list-decimal list-inside mt-1 space-y-0.5">
              <li>Go to your Dashboard</li>
              <li>Click <strong>Withdraw</strong> next to your USDC or CLT balance</li>
              <li>Confirm in your wallet — funds arrive on-chain within minutes</li>
            </ol>
            There is no lockup period. You can withdraw any time after resolution.
          </>
        ),
      },
      {
        q: "Which markets are allowed?",
        a: "You can launch a market on almost any current events or community topic. We reject spam and inappropriate content. Our team moderates to keep the platform clean.",
      },
      {
        q: "What is bookmaking on OMdot.fun?",
        a: "You can act as a bookmaker for streamer events, community games, live betting, and limits designed for communities.",
      },
      {
        q: "Is OMdot.fun available in my country?",
        a: (
          <>
            OMdot.fun is accessible globally. It is your responsibility to ensure that using a prediction market platform complies with the laws of your jurisdiction. Nothing on this platform constitutes financial advice or a regulated financial product. If in doubt, consult a legal professional in your country.
          </>
        ),
      },
    ],
  },
  {
    title: "Launchpad",
    items: [
      {
        q: "What is the OMdot.fun Launchpad?",
        a: "The Launchpad is our dedicated phase for creating tokens on Solana. You can launch a memecoin, a startup, a tokenized asset, or a community project.",
      },
      {
        q: "How much does it cost to launch a token?",
        a: "0.08 SOL — one of the lowest thresholds on the network.",
      },
      {
        q: "How much does the token creator earn?",
        a: "500 Omero as soon as the token is created, plus 1% of every transaction on your token as long as it trades.",
      },
      {
        q: "What are the trading fees on a token launched on OMdot.fun?",
        a: (
          <>
            We take 2.5% on each trade, split as follows:
            <ul className="list-disc list-inside mt-1 space-y-0.5">
              <li>1% → Creator</li>
              <li>1% → Platform activity</li>
              <li>0.5% → Meteora</li>
            </ul>
            In Meteora&apos;s program, 20% of the 2.5% goes to them — that is their standard model.
          </>
        ),
      },
      {
        q: "What happens after launch — does the token graduate?",
        a: (
          <>
            Tokens launched on OMdot.fun use Meteora&apos;s Dynamic Bonding Curve (DBC). As trading volume grows, the token progresses along the curve. When it reaches the graduation threshold, liquidity migrates automatically to a Solana DEX, where the token trades freely on the open market. You do not need to do anything — graduation is automatic and on-chain.
          </>
        ),
      },
      {
        q: "What are OMdot.fun's 1% used for?",
        a: (
          <>
            OMdot.fun&apos;s 1% funds the real activity of the platform:
            <ul className="list-disc list-inside mt-1 space-y-0.5">
              <li>Omero rewards (token creation, markets, invite campaigns)</li>
              <li>Platform operations (on-chain infra, product, moderation, support)</li>
              <li>Treasury (USDC / SOL reserve)</li>
              <li>A return to activity: part can go back to traders and active communities</li>
            </ul>
            The creator is paid on every trade, and our share keeps Omero, the platform, and the community alive.
          </>
        ),
      },
      {
        q: "Is it more expensive than Pump.fun or Bags?",
        a: (
          <>
            The total 2.5% fee is higher than Pump.fun (~1.25% on the bonding curve) and often slightly higher than Bags (~2%). The difference is the split: the creator receives a fixed 1% on every transaction, Meteora receives 0.5%, and OMdot.fun receives 1% reinvested as described above. We do not claim to be the cheapest launchpad — we clearly show who gets what.
          </>
        ),
      },
      {
        q: "Is launching complicated?",
        a: "No. We designed a simple, fast setup for builders and memecoin creators alike.",
      },
    ],
  },
  {
    title: "Omero rewards",
    items: [
      {
        q: "What is Omero?",
        a: (
          <>
            Omero is OMdot.fun&apos;s rewards system — not a tradeable token yet, but a point system that tracks your contribution to the platform. You earn Omero for creating tokens, trading on prediction markets, inviting others, and participating in campaigns. The more you use $ClawdTrust, the more Omero you earn.
          </>
        ),
      },
      {
        q: "How do I earn Omero?",
        a: (
          <ul className="list-disc list-inside space-y-0.5">
            <li>500 Omero for creating a token on the Launchpad</li>
            <li>Omero for creating and betting on prediction markets</li>
            <li>Bonus Omero when you use $ClawdTrust instead of USDC</li>
            <li>Invite campaigns — bonus Omero for referring active users</li>
          </ul>
        ),
      },
      {
        q: "What can I do with Omero?",
        a: (
          <>
            Omero currently tracks your rank and activity on the platform. Future utility (rewards, conversions, exclusive access) will be announced. Omero does not expire and accumulates across all your activity. Follow{" "}
            <a
              href="https://x.com/OMdotFun"
              target="_blank"
              rel="noopener noreferrer"
              className="text-violet-600 dark:text-violet-400 underline underline-offset-2"
            >
              @OMdotFun
            </a>{" "}
            for updates.
          </>
        ),
      },
    ],
  },
  {
    title: "Verification badge",
    items: [
      {
        q: "What is the verification badge?",
        a: (
          <>
            Some tokens launched on OMdot.fun can receive a verification badge indicating that the team has reviewed the project and that the token matches its official creator. On OMdot.fun, a token name cannot be used twice — the first person to launch a name owns it.
            <br /><br />
            The badge is <strong>not</strong> a guarantee of profit, a security audit, investment advice, or protection against loss. Always check the contract, the team, and the terms before trading.
          </>
        ),
      },
      {
        q: "Who can request a badge?",
        a: "The token creator, from the wallet that launched it on OMdot.fun. No one else can request the badge on their behalf.",
      },
      {
        q: "What are the requirements?",
        a: (
          <ul className="list-disc list-inside space-y-0.5">
            <li>Token was launched on OMdot.fun</li>
            <li>Creator controls the creation wallet</li>
            <li>Name, ticker, logo, and description are clear and stable</li>
            <li>Not a copy of an already verified token or a misleading namesake</li>
            <li>Creator has an identifiable X and/or Discord linked to the project</li>
            <li>Content is not spam, impersonation, or a forbidden topic</li>
            <li>No suspicious behavior (abusive mint, opaque freeze, misleading metadata, drain, etc.)</li>
            <li>Project shows real activity: community, communication, or clear utility</li>
          </ul>
        ),
      },
      {
        q: "How do I request the badge?",
        a: (
          <ol className="list-decimal list-inside space-y-1">
            <li>Launch your token on omdot.fun</li>
            <li>Prepare the contract, creator wallet, X / Discord link, and a short project presentation</li>
            <li>Send the request through official channels (Discord or the form on the site)</li>
            <li>Wait for the team review</li>
          </ol>
        ),
      },
      {
        q: "How long does it take?",
        a: "The review delay depends on the volume of requests and the clarity of the file. An incomplete, vague, or copied file will be rejected.",
      },
      {
        q: "Can the badge be removed?",
        a: "Yes. We can remove the badge at any time if the project changes identity to deceive, the team abandons or rugs, the contract is used against holders, or the request was false.",
      },
      {
        q: "Are all OMdot.fun tokens verified?",
        a: "No. Most tokens do not have a badge. The badge is a clarity filter, not a ranking of the best tokens.",
      },
      {
        q: "What should I do if I see a fake token?",
        a: "Always compare the contract shown on omdot.fun, the creator wallet, and the official X and Discord links. If a token copies a verified project, report it to the team.",
      },
    ],
  },
  {
    title: "General",
    items: [
      {
        q: "Is OMdot.fun on-chain?",
        a: "Yes. Creation and trading happen on-chain on Solana. This means no central server controls your funds — everything is settled by smart contracts and verifiable by anyone.",
      },
      {
        q: "Which wallets should I use?",
        a: (
          <>
            <strong>Solflare</strong> (recommended) —{" "}
            <a
              href="https://solflare.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-violet-600 dark:text-violet-400 underline underline-offset-2"
            >
              solflare.com
            </a>
            <br />
            <strong>Phantom</strong> (also supported) —{" "}
            <a
              href="https://phantom.app"
              target="_blank"
              rel="noopener noreferrer"
              className="text-violet-600 dark:text-violet-400 underline underline-offset-2"
            >
              phantom.app
            </a>
            <br />
            We also support Backpack, OKX Wallet, Coinbase Wallet, and Trust Wallet. Install the browser extension for your wallet, then click <strong>Connect Wallet</strong> on any page. You will need a small amount of SOL for network fees (~0.001 SOL per transaction).
          </>
        ),
      },
      {
        q: "Is there a referral program?",
        a: "Yes. You earn 1% of your referrals' creation revenue. We also regularly run invite campaigns with Omero bonuses.",
      },
      {
        q: "Where can I follow OMdot.fun?",
        a: (
          <ul className="list-disc list-inside space-y-0.5">
            <li>Website: <a href="https://omdot.fun" className="text-violet-600 dark:text-violet-400 underline underline-offset-2">omdot.fun</a></li>
            <li>X: <a href="https://x.com/OMdotFun" target="_blank" rel="noopener noreferrer" className="text-violet-600 dark:text-violet-400 underline underline-offset-2">@OMdotFun</a></li>
            <li>Telegram (news): <a href="https://t.me/Omdotfun" target="_blank" rel="noopener noreferrer" className="text-violet-600 dark:text-violet-400 underline underline-offset-2">t.me/Omdotfun</a></li>
            <li>Telegram (tutorials): <a href="https://t.me/OmdotfunTuto" target="_blank" rel="noopener noreferrer" className="text-violet-600 dark:text-violet-400 underline underline-offset-2">t.me/OmdotfunTuto</a></li>
            <li>Discord: link available in our official bio</li>
          </ul>
        ),
      },
    ],
  },
];

export default function FaqPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-8 pb-24 space-y-10">
      {/* Header */}
      <div className="space-y-2">
        <h1 className="text-2xl font-bold text-foreground">Official FAQ</h1>
        <p className="text-sm text-muted-foreground leading-relaxed">
          We are building an on-chain platform on Solana that brings together prediction markets and a Launchpad.
          Our goal is simple: let you create, trade, and earn on the real activity of your community.
        </p>
        <div className="flex flex-wrap gap-3 pt-1">
          <a
            href="https://omdot.fun"
            className="inline-flex items-center gap-1 text-xs text-violet-600 dark:text-violet-400 hover:underline"
          >
            omdot.fun <ExternalLink className="size-3" />
          </a>
          <a
            href="https://x.com/OMdotFun"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-xs text-violet-600 dark:text-violet-400 hover:underline"
          >
            @OMdotFun <ExternalLink className="size-3" />
          </a>
        </div>
      </div>

      {/* Sections */}
      {SECTIONS.map((section) => (
        <section key={section.title} className="space-y-3">
          <h2 className="text-base font-semibold text-foreground border-b border-border pb-2">
            {section.title}
          </h2>
          <div className="space-y-4">
            {section.items.map((item) => (
              <div key={item.q} className="space-y-1">
                <h3 className="text-sm font-semibold text-foreground">{item.q}</h3>
                <div className="text-sm text-muted-foreground leading-relaxed">{item.a}</div>
              </div>
            ))}
          </div>
        </section>
      ))}

      {/* Disclaimer */}
      <p className="text-xs text-muted-foreground border-t border-border pt-6">
        ⚠️ Trading prediction markets and launching a token involve a risk of loss. Always check the current terms on{" "}
        <Link href="/" className="text-violet-600 dark:text-violet-400 hover:underline">omdot.fun</Link>{" "}
        before acting.
      </p>
    </main>
  );
}
